/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Crypto checkout",
  "tagline": "Crypto payments",
  "url": "https://docs.dyte.io",
  "baseUrl": "/",
  "favicon": "/favicon.ico",
  "i18n": {
    "defaultLocale": "es",
    "locales": [
      "es"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    null,
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "cli",
        "path": "docs/cli",
        "routeBasePath": "/cli"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "plugin-sdk",
        "path": "docs/plugin-sdk",
        "routeBasePath": "/plugin-sdk",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "ui-kit",
        "path": "docs/ui-kit",
        "routeBasePath": "/ui-kit",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "react-ui-kit",
        "path": "docs/react-ui-kit",
        "routeBasePath": "/react-ui-kit",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "angular-ui-kit",
        "path": "docs/angular-ui-kit",
        "routeBasePath": "/angular-ui-kit",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "web-core",
        "path": "docs/web-core",
        "routeBasePath": "/web-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "react-web-core",
        "path": "docs/react-web-core",
        "routeBasePath": "/react-web-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "android-core",
        "path": "docs/android-core",
        "routeBasePath": "/android-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "flutter-core",
        "path": "docs/flutter-core",
        "routeBasePath": "/flutter-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "ios-core",
        "path": "docs/ios-core",
        "routeBasePath": "/ios-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "rn-core",
        "path": "docs/rn-core",
        "routeBasePath": "/rn-core",
        "versions": {
          "current": {
            "label": "1.x.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "android",
        "path": "docs/android",
        "routeBasePath": "/android",
        "versions": {
          "current": {
            "label": "0.14.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "flutter",
        "path": "docs/flutter",
        "routeBasePath": "/flutter",
        "versions": {
          "current": {
            "label": "0.7.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "ios",
        "path": "docs/ios",
        "routeBasePath": "/ios",
        "versions": {
          "current": {
            "label": "1.33.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "react-native",
        "path": "docs/react-native",
        "routeBasePath": "/react-native",
        "versions": {
          "current": {
            "label": "0.25.x"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "react",
        "path": "docs/react",
        "routeBasePath": "/react",
        "versions": {
          "current": {
            "label": "0.37.0"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": false,
        "editUrl": "https://github.com/dyte-in/docs/tree/main/",
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js",
        "id": "javascript",
        "path": "docs/javascript",
        "routeBasePath": "/javascript",
        "versions": {
          "current": {
            "label": "0.37.0"
          }
        }
      }
    ],
    null
  ],
  "trailingSlash": false,
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "clientModules": [
    "/home/arturo/git/documentacion/crypto-checkout-docs/src/client/define-ui-kit.js"
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs/guides",
          "id": "guides",
          "routeBasePath": "/guides",
          "breadcrumbs": false,
          "editUrl": "https://github.com/dyte-in/docs/tree/main/",
          "showLastUpdateTime": true,
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "sidebarPath": "/home/arturo/git/documentacion/crypto-checkout-docs/sidebars-default.js"
        },
        "blog": false,
        "theme": {
          "customCss": [
            "/home/arturo/git/documentacion/crypto-checkout-docs/src/css/custom.css",
            "/home/arturo/git/documentacion/crypto-checkout-docs/src/css/api-reference.css"
          ]
        },
        "sitemap": {
          "ignorePatterns": [
            "/tags/**"
          ]
        },
        "googleTagManager": {
          "containerId": "GTM-5FDFFSS"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "/img/koibanx-naranja.png",
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "href": "/",
        "src": "/logo/koibanx.svg",
        "srcDark": "/logo/koibanx.svg",
        "alt": "Dyte Docs",
        "height": "40px",
        "width": "101px"
      },
      "items": [
        {
          "label": "Guia",
          "to": "guides/quickstart",
          "position": "left"
        },
        {
          "label": "API Reference",
          "to": "/api/",
          "position": "left"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "label": "Dashboard",
          "href": "https://dev.dyte.io/register",
          "position": "right",
          "className": "dev-portal-signup dev-portal-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "logo": {
        "href": "/",
        "src": "/logo/koibanx.svg",
        "srcDark": "/logo/koibanx.svg",
        "alt": "Dyte Docs",
        "height": "36px"
      },
      "links": [
        {
          "title": "Product",
          "items": [
            {
              "label": "Demo",
              "href": "https://app.dyte.io"
            },
            {
              "label": "Developer Portal",
              "href": "https://dev.dyte.io"
            },
            {
              "label": "Pricing",
              "href": "https://dyte.io/#pricing"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About Us",
              "href": "https://dyte.io"
            },
            {
              "label": "Join Us",
              "href": "https://dyte.freshteam.com/jobs"
            },
            {
              "label": "Privacy Policy",
              "href": "https://dyte.io/privacy-policy"
            },
            {
              "label": "Contact Us",
              "href": "https://dyte.io/contact"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Documentation",
              "href": "/"
            },
            {
              "label": "Blog",
              "href": "https://dyte.io/blog"
            },
            {
              "label": "Community",
              "href": "https://community.dyte.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © Dyte since 2020. All rights reserved.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "dart",
        "ruby",
        "groovy",
        "kotlin",
        "java",
        "swift",
        "objectivec"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "highlight-next-line-error"
        }
      ]
    },
    "algolia": {
      "appId": "HL0HSV62RK",
      "apiKey": "72ebf02146698733b7114c7b36da0945",
      "indexName": "docs",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "webpack": {},
  "baseUrlIssueBanner": true,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
